# Generated by Django 2.2.11 on 2020-10-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followList',
            new_name='followerList',
        ),
        migrations.AddField(
            model_name='profile',
            name='followingList',
            field=models.TextField(default='0@'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='did', to='accounts.Profile'),
        ),
    ]
